import {DatabaseSync} from 'node:sqlite';
import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {scryptSync} from 'node:crypto';
import {createAuthServer} from './index.mjs';
import {hashPassword,checkPassword,totp,base32,validStep,encrypt,decrypt,digest} from './crypto.mjs';
const directory=mkdtempSync(join(tmpdir(),'coin-auth-test-'));const origin='http://127.0.0.1:5175';const server=await createAuthServer({directory,origin});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url=`http://127.0.0.1:${server.address().port}/api/auth/`;
after(async()=>{await new Promise(resolve=>server.close(resolve));rmSync(directory,{recursive:true,force:true});});
async function request(path,body,headers={}){const r=await fetch(url+path,{method:body?'POST':'GET',headers:{Origin:origin,...(body?{'Content-Type':'application/json'}:{}),...headers},body:body?JSON.stringify(body):undefined});return {status:r.status,value:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
async function challenge(){const c=await request('challenge');return {challenge:c.value.id,answer:String(c.value.prompt.split(' + ').map(Number).reduce((a,b)=>a+b))};}
const email='test@example.com',password='Test-account-only-123456';let session,secret,codes;
test('scrypt validates passwords and rejects wrong credentials',async()=>{const hash=await hashPassword(password);assert.ok(!hash.includes(password));assert.ok(await checkPassword(password,hash));assert.equal(await checkPassword('wrong',hash),false);});
test('preserves access to legacy hashes during password-hash upgrade',async()=>{const salt='0123456789abcdef0123456789abcdef';const hash=scryptSync(password,salt,64,{N:32768,maxmem:64*1024*1024}).toString('hex');assert.ok(await checkPassword(password,`${salt}:${hash}`));assert.ok((await hashPassword(password)).startsWith('scrypt-v2:'));});
test('TOTP matches RFC 6238 SHA1 vector and rejects replay',()=>{const key=base32(Buffer.from('12345678901234567890'));assert.equal(totp(key,1),'287082');assert.equal(validStep(key,'287082',-1,59000),1);assert.equal(validStep(key,'287082',1,59000),null);});
test('MFA secrets have authenticated encryption',()=>{const key=Buffer.alloc(32,1),cipher=encrypt('secret',key);assert.equal(decrypt(cipher,key),'secret');assert.throws(()=>decrypt(cipher,Buffer.alloc(32,2)));});
test('registration creates isolated user with HttpOnly session',async()=>{session=await request('register',{email,password,...await challenge()});assert.equal(session.status,200);assert.equal(session.value.user.owner,false);assert.equal(session.value.user.mfa,false);assert.ok(session.value.csrf);const r=await request('session',null,{Cookie:session.cookie});assert.equal(r.value.user.email,email);});
test('rejects SQL injection login and single-use CAPTCHA replay',async()=>{const c=await challenge();assert.equal((await request('login',{email:"' OR 1=1--",password,...c})).status,400);const body={email,password:'wrong',...c};assert.equal((await request('login',body)).status,401);assert.equal((await request('login',{email,password,...c})).status,200);assert.equal((await request('login',{email,password,...c})).status,400);});
test('rejects cross-origin requests and missing CSRF',async()=>{assert.equal((await request('logout',{}, {Cookie:session.cookie,Origin:'https://evil.example'})).status,403);assert.equal((await request('logout',{}, {Cookie:session.cookie})).status,403);});
test('MFA requires password, confirms proof, and returns recovery codes',async()=>{const headers={Cookie:session.cookie,'X-CSRF-Token':session.value.csrf};assert.equal((await request('mfa/start',{password:'wrong'},headers)).status,403);const start=await request('mfa/start',{password},headers);secret=start.value.secret;assert.ok(secret);const confirmed=await request('mfa/confirm',{code:totp(secret)},headers);assert.equal(confirmed.status,200);codes=confirmed.value.codes;assert.equal(codes.length,8);assert.equal((await request('session',null,{Cookie:session.cookie})).value.user.mfa,true);});
test('MFA enforces second factor and recovery codes are one-use',async()=>{const pending=await request('login',{email,password,...await challenge()});assert.equal(pending.status,200);assert.equal(pending.value.step,'mfa');assert.equal(pending.cookie,undefined);assert.equal((await request('login',{email,password,code:codes[0],...await challenge()})).status,200);assert.equal((await request('login',{email,password,code:codes[0],...await challenge()})).status,401);});
test('logout invalidates session',async()=>{assert.equal((await request('logout',{}, {Cookie:session.cookie,'X-CSRF-Token':session.value.csrf})).status,200);assert.equal((await request('session',null,{Cookie:session.cookie})).value.user,null);});
test('a second account cannot use the first account CSRF token',async()=>{const other=await request('register',{email:'other@example.com',password,...await challenge()});assert.equal(other.status,200);assert.notEqual(other.value.user.id,session.value.user.id);assert.equal((await request('logout',{}, {Cookie:other.cookie,'X-CSRF-Token':session.value.csrf})).status,403);assert.equal((await request('session',null,{Cookie:other.cookie})).value.user.email,'other@example.com');});
test('rejects oversized payloads and unexpected input fields',async()=>{assert.equal((await request('login',{email,password,unexpected:'field',...await challenge()})).status,400);assert.equal((await request('login',{email,password:'x'.repeat(9000),...await challenge()})).status,413);});
test('production rejects missing HTTPS and CAPTCHA configuration',async()=>{await assert.rejects(createAuthServer({directory,origin:'http://127.0.0.1:5175',production:true}));});
test('staged login issues no session before CAPTCHA and enabled MFA, and tickets are single use',async()=>{const first=await request('login',{email,password});assert.equal(first.status,200);assert.equal(first.value.step,'captcha');assert.equal(first.cookie,undefined);assert.equal((await request('verify',{verification:first.value.verification,code:codes[1]})).status,400);const second=await request('verify',{verification:first.value.verification,...await challenge()});assert.equal(second.value.step,'mfa');assert.equal(second.cookie,undefined);assert.equal((await request('verify',{verification:second.value.verification,code:'000000'})).status,401);const final=await request('verify',{verification:second.value.verification,code:codes[1]});assert.equal(final.status,200);assert.ok(final.cookie);assert.equal((await request('verify',{verification:second.value.verification,code:codes[1]})).status,401);});
test('expired verification tickets cannot issue a session',async()=>{const first=await request('login',{email:'other@example.com',password});assert.equal(first.value.step,'captcha');const store=new DatabaseSync(join(directory,'auth.sqlite'));store.prepare('UPDATE pending_auth SET expires=0 WHERE hash=?').run(digest(first.value.verification));store.close();const result=await request('verify',{verification:first.value.verification,...await challenge()});assert.equal(result.status,401);assert.equal(result.cookie,undefined);});
test('login attempts are throttled',async()=>{let status=0;for(let i=0;i<12&&status!==429;i++)status=(await request('login',{email,password:'wrong',...await challenge()})).status;assert.equal(status,429);});

test('shared API requires authenticated session and CSRF, including reads',async()=>{assert.equal((await request('shared',{action:'status'})).status,403);assert.equal((await request('shared',{action:'status'},{Cookie:'coin_session=invalid','X-CSRF-Token':'forged'})).status,403);assert.equal((await request('shared',{action:'status'},{Origin:'https://attacker.example'})).status,403);});
