import {it,expect} from 'vitest';
import {inferArea,areaTotals,installmentPlan} from './budgetAreas';
import {entity,seed} from './test-fixtures';
import {entitySchema,settingsSchema,type Transaction} from './model';
it('organizes specific expense items without confusing family rent with household rent',()=>{expect(inferArea('Renta Madre')).toBe('Familia');expect(inferArea('Alquiler / hipoteca')).toBe('Renta');expect(inferArea('Veterinario / Grooming')).toBe('Mascota');expect(inferArea('Supermercado')).toBe('Alimentación');expect(inferArea('Internet y móvil')).toBe('Servicios');});
it('counts only actual selected-month expenses by editable general area',()=>{const s=seed(),c=s.entities.find(e=>e.name==='Supermercado')!,a=s.entities.find(e=>e.kind==='account')!;const t:Transaction={id:crypto.randomUUID(),name:'Food',type:'expense',amount:100,currency:'GTQ',fx:7.6,date:'2026-10-05',accountId:a.id,categoryId:c.id,targetId:'',member:'Shared',share:50,note:''};s.transactions=[t,{...t,id:crypto.randomUUID(),date:'2026-10-25'}];expect(areaTotals(s,'2026-10','2026-10-06').find(r=>r.name==='Alimentación')?.spent).toBe(100);c.budgetArea='Custom';expect(areaTotals(s,'2026-10','2026-10-06').find(r=>r.name==='Custom')?.spent).toBe(100);});
it('supports optional installments, partial final payments, and uncovered principal',()=>{const s=seed();const debt=entity('debt','Family',1000,{installments:{months:3,monthly:300,start:'2026-10-15'}});expect(installmentPlan(debt,s,'2026-10-06')?.uncovered).toBe(100);debt.installments!.months=4;expect(installmentPlan(debt,s,'2026-10-06')?.rows.at(-1)?.remaining).toBe(0);expect(installmentPlan(entity('debt','Other',100),s,'2026-10-06')).toBeNull();expect(entitySchema.safeParse({...debt,installments:{months:0,monthly:0,start:'2026-02-31'}}).success).toBe(false);});
it('accepts four themes and rejects duplicate general categories',()=>{for(const theme of ['dark','light','midnight','sand'])expect(settingsSchema.safeParse({...seed().settings,theme}).success).toBe(true);expect(settingsSchema.safeParse({...seed().settings,budgetAreas:['Food','food']}).success).toBe(false);});

it('clamps monthly installment dates and keeps the original day for later months',()=>{const s=seed(),debt=entity('debt','Installment',1000,{installments:{months:4,monthly:300,start:'2027-01-31'}});const rows=installmentPlan(debt,s,'2026-10-06')!.rows;expect(rows.map(r=>r.date)).toEqual(['2027-01-31','2027-02-28','2027-03-31','2027-04-30']);expect(rows.at(-1)?.payment).toBe(100);});
it('disabling a category removes its planned limit but preserves historical spending and group',()=>{const s=seed(),c=s.entities.find(e=>e.name==='Supermercado')!,a=s.entities.find(e=>e.kind==='account')!;c.budgetArea='Alimentación';const before=areaTotals(s,'2026-10','2026-10-06').find(r=>r.name==='Alimentación')!.budget;s.transactions=[{id:crypto.randomUUID(),name:'Food',type:'expense',amount:100,currency:'GTQ',fx:7.6,date:'2026-10-05',accountId:a.id,categoryId:c.id,targetId:'',member:'Shared',share:100,note:''}];c.active=false;const after=areaTotals(s,'2026-10','2026-10-06').find(r=>r.name==='Alimentación')!;expect(after.budget).toBe(before-c.amount);expect(after.spent).toBe(100);c.active=true;expect(areaTotals(s,'2026-10','2026-10-06').find(r=>r.name==='Alimentación')!.budget).toBe(before);});
