import {gtq,txGTQ,round,debtBalance,type Entity,type Snapshot} from './model';
export const defaultAreas=['Hogar','Alimentación','Servicios','Renta','Transporte','Salud','Familia','Mascota','Ocio','Personal','Otros'];
export const areaLabel=(name:string,es:boolean)=>es?name:({Hogar:'Household',Alimentación:'Food',Servicios:'Utilities',Renta:'Rent',Transporte:'Transport',Salud:'Health',Familia:'Family',Mascota:'Pet',Ocio:'Lifestyle',Personal:'Personal',Otros:'Other'}[name]??name);
export function inferArea(name:string){const n=name.toLowerCase();if(/madre|papá|padre|universidad|apoyo personal/.test(n))return 'Familia';if(/veterin|premios|grooming|mascota|pet food/.test(n))return 'Mascota';if(/alquiler|hipoteca|vivienda|^renta/.test(n))return 'Renta';if(/supermercado|comidas|restaur|alimenta/.test(n))return 'Alimentación';if(/electricidad|internet|móvil|telefon|servicios/.test(n))return 'Servicios';if(/combustible|transporte|seguro carro/.test(n))return 'Transporte';if(/salud|medicin|seguro/.test(n))return 'Salud';if(/limpieza|artículos hogar|hogar/.test(n))return 'Hogar';if(/ocio|streaming|entreten/.test(n))return 'Ocio';if(/higiene|cabello|ropa|zapatos|cuidado personal/.test(n))return 'Personal';return 'Otros';}
export function areaTotals(data:Snapshot,month:string,asOf:string){
 const categories=data.entities.filter(e=>e.kind==='category');const map=new Map(categories.map(e=>[e.id,e.budgetArea??inferArea(e.name)]));
 const totals=new Map([...new Set([...(data.settings.budgetAreas??defaultAreas),...map.values(),'Otros'])].map(name=>[name,{name,spent:0,budget:0}]));
 for(const c of categories.filter(c=>c.active))totals.get(map.get(c.id)!)!.budget+=gtq(c.amount,c.currency,data.settings.fx);
 for(const t of data.transactions)if(t.type==='expense'&&t.date.startsWith(month)&&t.date<=asOf)totals.get(map.get(t.categoryId)??'Otros')!.spent+=txGTQ(t);
 return [...totals.values()].map(r=>({...r,spent:round(r.spent),budget:round(r.budget)}));
}
export function installmentPlan(debt:Entity,data:Snapshot,asOf:string){const plan=debt.installments;if(!plan)return null;const remaining=debtBalance(debt,data.transactions.filter(t=>t.date<=asOf),data.settings.fx);const monthly=gtq(plan.monthly,debt.currency,data.settings.fx);if(monthly<=0)return {remaining,monthly,rows:[],uncovered:remaining};const rows=Array.from({length:Math.min(plan.months,Math.ceil(remaining/monthly))},(_,i)=>{const start=new Date(plan.start+'T12:00:00'),d=new Date(start.getFullYear(),start.getMonth()+i,1,12);const day=Math.min(start.getDate(),new Date(d.getFullYear(),d.getMonth()+1,0).getDate());return {month:i+1,date:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`,payment:round(Math.min(monthly,Math.max(0,remaining-monthly*i))),remaining:round(Math.max(0,remaining-monthly*(i+1)))};});return {remaining,monthly,rows,uncovered:round(Math.max(0,remaining-monthly*plan.months))};}
