import {describe,it,expect} from 'vitest';
import {seed,entity} from './test-fixtures';
import {cashflow,scheduledEvents,isSettled,allocations} from './cashflow';
import type {Transaction} from './model';
describe('dated cash planning',()=>{
 it('clamps monthly day 31 to February and respects start',()=>{const s=seed();s.events=[];s.entities=[entity('recurring','Rent',300,{day:31,start:'2026-02-01'})];expect(scheduledEvents(s,'2026-02')[0].date).toBe('2026-02-28');expect(scheduledEvents(s,'2026-01')).toHaveLength(0);});
 it('does not invent semimonthly dates or unknown bimonthly anchors',()=>{const s=seed();s.events=[];expect(scheduledEvents(s,'2026-11').filter(e=>['Employer B','Employer C','Contract D'].includes(e.name))).toHaveLength(0);});
 it('a dated override replaces an automatic occurrence',()=>{const s=seed();const source=s.entities.find(e=>e.name==='Employer A')!;expect(scheduledEvents(s,'2026-10').filter(e=>e.sourceId===source.id)).toHaveLength(1);});
 it('does not double-count an income after recording receipt',()=>{const s=seed();const e=s.events.find(e=>e.name==='Employer A')!;const account=s.entities.find(e=>e.kind==='account')!;s.transactions=[{id:crypto.randomUUID(),name:e.name,type:'income',amount:e.amount,currency:e.currency,fx:s.settings.fx,date:e.date,accountId:account.id,targetId:'',categoryId:'',member:'Member',share:100,note:'',eventId:e.id} satisfies Transaction];expect(isSettled(s,e)).toBe(true);expect(cashflow(s,'2026-10','2026-10-25').timeline.filter(r=>r.name==='Employer A')).toHaveLength(1);});
 it('excludes pending cash and flags expense due before income',()=>{const s=seed();const account=entity('account','Cash',100);const expense=entity('recurring','Rent',200,{day:10});const income=entity('recurring','Salary',1000,{day:20,flow:'income'});s.entities=[account,expense,income];s.transactions=[];s.events=[{id:crypto.randomUUID(),name:'Uncertain',date:'2026-10-09',amount:2000,currency:'GTQ',flow:'income',status:'pending',sourceId:''}];const result=cashflow(s,'2026-10','2026-10-01');expect(result.minimum).toBe(-100);expect(result.timeline.find(r=>r.name==='Rent')?.funding).toContain('Opening');expect(result.timeline.at(-1)?.balance).toBe(900);});
 it('keeps unpaid past-due commitments visible in current analysis',()=>{const s=seed();expect(cashflow(s,'2026-10','2026-10-06').timeline.some(r=>r.name.includes('Card B'))).toBe(true);});
 it('projects every event in a past month from its opening balance',()=>{expect(cashflow(seed(),'2026-10','2026-11-10').timeline.some(r=>r.name==='Employer A')).toBe(true);});
 it('moving a generated occurrence does not duplicate the original date',()=>{const s=seed();s.events=[];const source=s.entities.find(e=>e.name==='Employer A')!;s.events=[{id:crypto.randomUUID(),name:'Employer A',date:'2026-11-26',occurrenceDate:'2026-11-25',amount:2900,currency:'USD',flow:'income',status:'confirmed',sourceId:source.id}];expect(scheduledEvents(s,'2026-11').filter(e=>e.sourceId===source.id)).toHaveLength(1);});
 it('allocates across receipts without spending the same liquidity twice',()=>{const s=seed();s.events=[];s.transactions=[];s.entities=[entity('account','Cash',1000),entity('category','Food',10000),entity('recurring','Salary',1000,{day:15,flow:'income'}),entity('recurring','Bill',500,{day:28})];const result=allocations(s,'2026-10','2026-10-01');expect(result.windows.reduce((n,w)=>n+w.amount,0)).toBeLessThanOrEqual(1500);expect(result.windows[0].amount).toBeLessThanOrEqual(1000);});
 it('protects emergency reserve and handles the last day of month',()=>{const s=seed();s.events=[];s.transactions=[];s.entities=[entity('account','Cash',6000),entity('category','Food',3000),entity('goal','Mini fondo emergencia',5000)];const result=allocations(s,'2026-10','2026-10-31');expect(result.windows).toHaveLength(1);expect(result.windows[0].amount).toBe(1000);});
});
