import 'fake-indexeddb/auto';
import {it,expect,afterEach} from 'vitest';
import {db,initialize,snapshot,replaceSnapshot,selectDatabase} from './db';
import {seed} from './test-fixtures';
afterEach(async()=>{await db.delete();await db.open();});
it('seeds once and preserves edits across initialization',async()=>{await initialize();const before=await snapshot();const a=before.entities.find(e=>e.kind==='account')!;await db.entities.update(a.id,{amount:1234});await initialize();const after=await snapshot();expect(after.entities).toHaveLength(before.entities.length);expect(after.entities.find(e=>e.id===a.id)?.amount).toBe(1234);});
it('rejects invalid restore without changing persisted data',async()=>{await initialize();const before=await snapshot();await expect(replaceSnapshot({...before,entities:[{bad:true}]})).rejects.toThrow();expect(await snapshot()).toEqual(before);});
it('replaces an entire valid backup atomically',async()=>{await initialize();const next=seed();next.settings.language='en';await replaceSnapshot(next);expect(await snapshot()).toEqual({...next,entities:[...next.entities].sort((a,b)=>a.id.localeCompare(b.id)),events:[...next.events].sort((a,b)=>a.id.localeCompare(b.id))});});
it('upgrades existing budget amounts once while preserving category and transaction references',async()=>{const s=seed();s.settings.budgetRevision=undefined;const category=s.entities.find(e=>e.name==='Ocio')!;category.amount=1000;await replaceSnapshot(s);await initialize();const migrated=(await snapshot()).entities.find(e=>e.id===category.id)!;expect(migrated.name).toBe('Ocio');expect(migrated.amount).toBe(1000);await db.entities.update(category.id,{amount:2700});await initialize();expect((await snapshot()).entities.find(e=>e.id===category.id)?.amount).toBe(2700);});

it('preserves optional installment terms, general areas and themes through backup replacement',async()=>{const s=seed(),debt=s.entities.find(e=>e.kind==='debt')!,category=s.entities.find(e=>e.kind==='category')!;debt.installments={months:6,monthly:500,start:'2026-10-31'};category.budgetArea='Custom';s.settings.theme='sand';s.settings.budgetAreas=['Custom','Otros'];await replaceSnapshot(s);const stored=await snapshot();expect(stored.entities.find(e=>e.id===debt.id)?.installments).toEqual(debt.installments);expect(stored.entities.find(e=>e.id===category.id)?.budgetArea).toBe('Custom');expect(stored.settings.theme).toBe('sand');});

it('keeps owner debts separate from guest and reloads the same owner records',async()=>{await replaceSnapshot(seed());await initialize();const before=(await snapshot()).entities.filter(e=>e.kind==='debt');expect(before).toHaveLength(6);selectDatabase('debt-isolation-test');await initialize(true);expect((await snapshot()).entities.filter(e=>e.kind==='debt')).toHaveLength(0);await db.delete();selectDatabase('owner',true);await initialize();expect((await snapshot()).entities.filter(e=>e.kind==='debt').map(e=>e.id)).toEqual(before.map(e=>e.id));});
