import {cashflow,allocations} from './cashflow';
import type {Snapshot} from './model';
export function FundingView({data,month,asOf,es,money}:{data:Snapshot;month:string;asOf:string;es:boolean;money:(n:number)=>string}){
 const say=(a:string,b:string)=>es?a:b;const plan=cashflow(data,month,asOf);const distribution=allocations(data,month,asOf);const categoryBudget=distribution.budget;
 return <section className="card funding"><div className="section-title"><h3>{say('Distribuye tu mes','Spread your month')}</h3><span className="badge">{say('Actualización en vivo','Live update')}</span></div><p className="muted">{say('Cubre primero las fechas obligatorias. Distribuye el presupuesto variable entre cobros y conserva liquidez; las sugerencias no cambian pagos automáticamente.','Cover fixed due dates first. Spread variable budgets between receipts and preserve liquidity; suggestions never change payments automatically.')}</p><details className="optional-panel"><summary>{say('Ver reservas y reparto por fechas','View reserves and dated allocations')} · {say('Saldo mínimo: ','Lowest balance: ')}{money(plan.minimum)}</summary><div className="stats" style={{marginTop:20}}><div><small>{say('Saldo al inicio del análisis','Opening analysis balance')}</small><h2>{money(plan.opening)}</h2></div><div><small>{say('Saldo mínimo proyectado','Lowest projected balance')}</small><h2 className={plan.minimum<0?'danger':'positive'}>{money(plan.minimum)}</h2></div><div><small>{say('Presupuesto variable restante','Remaining variable budget')}</small><h2>{money(categoryBudget)}</h2></div></div>{plan.minimum<0&&<p className="danger">{say('Hay un faltante antes de cubrir todos los compromisos. Reduce compras flexibles o confirma ingresos adicionales; no retrases vencimientos obligatorios.','There is a shortfall before covering all commitments. Reduce flexible purchases or confirm extra income; do not delay mandatory due dates.')}</p>}
 <h3>{say('Reserva por fecha de pago','Reserve by due date')}</h3>{plan.timeline.filter(r=>r.flow==='expense').map(r=><div className="row" key={r.id}><div className="grow"><strong>{r.name}</strong><small>{r.date} · {say('Financiar con: ','Fund with: ')}{r.funding}</small></div><strong>{money(r.amount)}</strong><small className={r.balance<0?'danger':''}>{say('Saldo posterior: ','Balance after: ')}{money(r.balance)}</small></div>)}{plan.timeline.filter(r=>r.flow==='expense').length===0&&<p className="muted">{say('Marca gastos como repetitivos para ver qué reservar antes de cada vencimiento.','Mark expenses as recurring to see what to reserve before each due date.')}</p>}
 <h3 style={{marginTop:24}}>{say('Compras flexibles entre cobros','Flexible purchases between receipts')}</h3><small>{say('Reserva de emergencia por completar: ','Emergency reserve still needed: ')}{money(distribution.reserve)}</small>{distribution.windows.map(w=><div className="row" key={w.date}><div className="grow"><strong>{w.date} → {w.end} ({say('hasta antes del siguiente cobro','until before next receipt')})</strong><small>{say('Reparto de presupuesto: ','Budget share: ')}{money(w.desired)}</small><details className="optional-panel"><summary>{say('Ver cuánto destinar por categoría','View allocation by category')}</summary>{w.categories.map(c=><div className="plan-row" key={c.id}><span>{c.name}</span><strong>{money(c.amount)}</strong></div>)}</details></div><div className="align-right"><strong>{money(w.amount)}</strong><small>{say('Por día: ','Per day: ')}{money(w.amount/Math.max(1,(Date.parse(w.end)-Date.parse(w.date))/86400000))}</small><small>{say('Máximo orientativo según liquidez','Indicative maximum given liquidity')}</small></div></div>)}
 <small>{say('El presupuesto variable no se considera gastado. Los cobros pendientes se excluyen y los saldos iniciales deben estar conciliados. Un cobro el mismo día se supone disponible antes del gasto: confirma horarios bancarios.','Variable budgets are not considered spent. Pending receipts are excluded and opening balances must be reconciled. Same-day receipts are assumed available before expenses: check bank timing.')}</small>
 </details></section>;
}
