import {useEffect,useRef,useState} from 'react';
import {ChevronDown,Settings,LogOut,Sun,Languages,ArrowLeftRight,UserRound} from 'lucide-react';
import {useAuth} from './Auth';
import {type Settings as Preferences} from './model';
export function ProfileMenu({settings,onSettings,onUpdate,onError}:{settings:Preferences;onSettings:()=>void;onUpdate:(s:Partial<Preferences>)=>Promise<void>;onError:(message:string)=>void}){
 const {session,logout}=useAuth();const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const root=useRef<HTMLDivElement>(null);const trigger=useRef<HTMLButtonElement>(null);const es=settings.language==='es';const name=settings.profileName??(session.user?.owner?'Carlos':session.user?.email.split('@')[0]??(es?'Mi perfil':'My profile'));
 useEffect(()=>{if(!open)return;const close=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false);};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);trigger.current?.focus();}};document.addEventListener('pointerdown',close);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',escape);};},[open]);
 return <div className="profile" ref={root}><button ref={trigger} className="profile-trigger" aria-expanded={open} aria-controls="profile-panel" onClick={()=>setOpen(!open)}><span className="avatar">{name.charAt(0).toUpperCase()}</span><span className="profile-name">{name}</span><ChevronDown size={14}/></button>{open&&<section id="profile-panel" className="profile-panel" aria-label={es?'Opciones de perfil':'Profile options'}><div className="profile-identity"><UserRound size={20}/><div><strong>{name}</strong><small>{session.user?.email??(es?'Modo local':'Local mode')}</small></div></div><button className="profile-option" onClick={()=>{onSettings();setOpen(false);}}><Settings size={18}/>{es?'Ajustes':'Settings'}</button><label className="profile-field"><span><Sun size={18}/>{es?'Tema':'Theme'}</span><select aria-label={es?'Tema del perfil':'Profile theme'} value={settings.theme} onChange={e=>void onUpdate({theme:e.target.value as Preferences['theme']})}>{[['dark','Obsidian'],['light','Pearl'],['midnight','Midnight'],['sand','Sand'],['system',es?'Sistema':'System']].map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label className="profile-field"><span><Languages size={18}/>{es?'Idioma':'Language'}</span><select aria-label={es?'Idioma del perfil':'Profile language'} value={settings.language} onChange={e=>void onUpdate({language:e.target.value as 'es'|'en'})}><option value="es">Español</option><option value="en">English</option></select></label><div className="profile-fx"><ArrowLeftRight size={18}/><div><strong>1 USD = Q {settings.fx.toFixed(4)}</strong><small>{settings.fxSource==='online'?(es?'En línea':'Online'):settings.fxSource==='manual'?(es?'Tipo de cambio manual':'Manual exchange rate'):(es?'Referencia histórica':'Historical reference')}</small><small>{settings.fxUpdated}</small></div></div><button className="profile-option danger" disabled={busy} onClick={async()=>{setBusy(true);try{await logout();}catch{onError(es?'No se pudo cerrar sesión. Intenta de nuevo.':'Could not sign out. Please retry.');}finally{setBusy(false);}}}><LogOut size={18}/>{es?'Cerrar sesión':'Sign out'}</button></section>}</div>;
}
