import {expect,it} from 'vitest';
import {spendingProjection} from './projections';
import {seed,entity,budgetRows} from './test-fixtures';
it('imports all spreadsheet amounts and retains separate provisions',()=>{expect(budgetRows().reduce((n,r)=>n+r[2],0)).toBe(5100);expect(seed().entities.filter(e=>e.kind==='category').reduce((n,r)=>n+r.amount,0)).toBe(8100);});
it('does not double count a recorded scheduled expense or invent actual receipts',()=>{const s=seed(),account=s.entities.find(e=>e.kind==='account')!;const recurring=entity('recurring','Rent',4000,{day:5,categoryId:s.entities.find(e=>e.kind==='category')!.id,txType:'expense'});s.entities.push(recurring);const id=`schedule:${recurring.id}:2026-10-05`;s.transactions.push({id:crypto.randomUUID(),name:'Rent',type:'expense',amount:4000,currency:'GTQ',fx:7.6,date:'2026-10-05',accountId:account.id,categoryId:recurring.categoryId!,targetId:'',member:'Shared',share:100,note:'',eventId:id});const p=spendingProjection(s,'2026-10','2026-10-06');expect(p.actual).toBe(4000);expect(p.planned).toBe(0);expect(p.projected).toBe(20666.67);});

import {monthsBetween,savingsProjection,savingsBaseline} from './projections';
it('maps calendar targets across years and keeps savings horizons equivalent',()=>{expect(monthsBetween('2026-10','2027-10')).toBe(12);expect(monthsBetween('2026-12','2027-01')).toBe(1);expect(Number.isNaN(monthsBetween('2026-10','2027-13'))).toBe(true);expect(savingsProjection(5000,1000,12).at(-1)?.value).toBe(17000);expect(savingsProjection(5000,1000,0)).toEqual([{month:0,value:5000}]);});
it('rejects invalid savings amounts and horizons',()=>{expect(()=>savingsProjection(0,-1,12)).toThrow();expect(()=>savingsProjection(0,0,601)).toThrow();expect(()=>savingsProjection(0,0,1.5)).toThrow();});
it('uses three complete months and excludes investment and current-month contributions',()=>{const data=seed();const savings=entity('goal','Savings',0,{goalType:'savings'}),investment=entity('goal','Investments',0,{goalType:'investment'});data.entities.push(savings,investment);const account=data.entities.find(e=>e.kind==='account')!;const tx=(date:string,targetId:string,amount:number)=>({id:crypto.randomUUID(),name:'Contribution',type:'contribution' as const,date,targetId,amount,currency:'GTQ' as const,fx:7.6,accountId:account.id,categoryId:'',member:'Shared',share:100,note:''});data.transactions=[tx('2026-09-05',savings.id,900),tx('2026-10-01',savings.id,2000),tx('2026-08-01',investment.id,6000),tx('2026-06-01',savings.id,3000)];expect(savingsBaseline(data,'2026-10-06').monthly).toBe(300);expect(savingsBaseline(data,'2026-10-06').income).toBe(24424.08);});
