import {createContext,useContext,useEffect,useRef,useState,type ReactNode} from 'react';
import {useLiveQuery} from 'dexie-react-hooks';
import {authRequest,useAuth} from './Auth';
import {snapshot,replaceSnapshot} from './db';
import {type Snapshot} from './model';
import {download,encodeBackup} from './services';
type Role='admin'|'contributor'|'viewer';
type Workspace={id:string;role:Role;revision:number;snapshot:Snapshot;members:{email:string;role:Role}[]};
const Context=createContext<{workspace:Workspace|null;error:string;activate:()=>Promise<void>;manage:(action:string,email:string,role?:Role)=>Promise<void>;reload:()=>Promise<void>}>({workspace:null,error:'',activate:async()=>{},manage:async()=>{},reload:async()=>{}});
export const useShared=()=>useContext(Context);
const preferences=(s:Snapshot['settings'])=>({language:s.language,theme:s.theme,displayCurrency:s.displayCurrency,profileName:s.profileName});
export function SharedBudget({children}:{children:ReactNode}){
 const {session}=useAuth();const [workspace,setWorkspace]=useState<Workspace|null>(null);const [ready,setReady]=useState(!session.user);const [error,setError]=useState('');const data=useLiveQuery(snapshot,[]);const baseline=useRef('');const state=useRef<Workspace|null>(null);const applying=useRef(false);const busy=useRef(false);
 const accept=async(w:Workspace|null)=>{if(!w){if(state.current)throw Error('Se retiró tu acceso. Cierra sesión. / Access revoked. Sign out.');return;}applying.current=true;const local=await snapshot();const merged={...w.snapshot,settings:{...w.snapshot.settings,...preferences(local.settings)}};baseline.current=JSON.stringify(merged);state.current=w;await replaceSnapshot(merged);setWorkspace(w);applying.current=false;};
 const request=async(body:unknown)=>authRequest('shared',body,session.csrf) as Promise<{workspace:Workspace|null}>;
 useEffect(()=>{if(!session.user)return;let cancelled=false;request({action:'status'}).then(async r=>{if(!cancelled)await accept(r.workspace);}).catch(e=>setError(e.message)).finally(()=>{if(!cancelled)setReady(true);});return()=>{cancelled=true;};},[session.user?.id]);
 useEffect(()=>{if(!data||!workspace||applying.current||error)return;const current=JSON.stringify(data);if(current===baseline.current)return;const timer=setTimeout(async()=>{if(busy.current)return;busy.current=true;try{const w=state.current!;const proposed={...data,settings:{...data.settings,...preferences(w.snapshot.settings)}};const r=await request({action:'save',revision:w.revision,snapshot:proposed});if(r.workspace){state.current=r.workspace;setWorkspace(r.workspace);baseline.current=current;}}catch(e){setError((e as Error).message);}finally{busy.current=false;}},650);return()=>clearTimeout(timer);},[data,workspace,error]);
 useEffect(()=>{if(!workspace||error)return;const timer=setInterval(async()=>{if(busy.current||applying.current||JSON.stringify(await snapshot())!==baseline.current)return;busy.current=true;try{const r=await request({action:'status'});if(!r.workspace||r.workspace.revision!==state.current?.revision||r.workspace.role!==state.current?.role)await accept(r.workspace);}catch(e){setError((e as Error).message);}finally{busy.current=false;}},10000);return()=>clearInterval(timer);},[workspace,error]);
 const reload=async()=>{download(await encodeBackup(await snapshot()),'coin-fix-unsynced.backup.json');const r=await request({action:'status'});await accept(r.workspace);setError('');};
 if(!ready)return <div className="loading">The Coin Fix · Preparando acceso compartido…</div>;
 return <Context.Provider value={{workspace,error,reload,activate:async()=>{const r=await request({action:'activate',snapshot:await snapshot()});await accept(r.workspace);},manage:async(action,email,role)=>{const r=await request({action,email,...(role?{role}:{})});if(r.workspace){state.current=r.workspace;setWorkspace(r.workspace);}}}}>{workspace&&<div className="sync-status">Presupuesto compartido · {workspace.role==='admin'?'Administrador':workspace.role==='contributor'?'Contribuyente':'Visualizador'} · v{workspace.revision} · {error?'Cambios pendientes':'Sincronización activa'}</div>}{error&&<div className="sync-warning" role="alert">{error} · Los cambios locales aún no están confirmados en el servidor.<button onClick={()=>void reload().catch(e=>setError(e.message))}>Guardar copia local y recargar</button></div>}{children}</Context.Provider>;
}
export function SharedMembers(){
 const {workspace,activate,manage}=useShared();const {session}=useAuth();const [email,setEmail]=useState('');const [role,setRole]=useState<Role>('contributor');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const perform=async(fn:()=>Promise<void>)=>{setBusy(true);try{await fn();setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <section className="card"><h3>Presupuesto compartido / Shared budget</h3>{!workspace?<><p>Comparte un presupuesto con permisos individuales. Al activar, se copia este presupuesto al servidor de esta instalación; las personas autorizadas tendrán acceso a sus datos financieros.</p>{session.user?.owner?<button className="secondary" disabled={busy} onClick={()=>void perform(activate)}>Activar presupuesto compartido</button>:<small>El administrador debe autorizar tu correo para darte acceso. Inicia sesión de nuevo después.</small>}</>:<><p>Rol: {workspace.role==='admin'?'Administrador':workspace.role==='contributor'?'Contribuyente':'Visualizador (puede registrar gastos)'} · Versión {workspace.revision}</p><small>Con conexión, los cambios se envían al servidor y se consultan cada 10 segundos. Sin conexión permanecen pendientes. Los conflictos requieren revisión.</small>{workspace.role==='admin'&&<><form onSubmit={e=>{e.preventDefault();void perform(async()=>{await manage('invite',email,role);setEmail('');});}}><label>Correo del usuario<input type="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Permisos<select value={role} onChange={e=>setRole(e.target.value as Role)}><option value="admin">Administrador · control completo</option><option value="contributor">Contribuyente · agregar ingresos y gastos</option><option value="viewer">Visualizador · consultar y agregar gastos</option></select></label><button className="secondary" disabled={busy}>Dar acceso / actualizar permisos</button></form><small>No se envía correo automáticamente. La persona debe crear su cuenta en esta misma instalación con este correo. No compartas contraseñas.</small>{workspace.members.map(m=><div className="row" key={m.email}><div className="grow"><strong>{m.email}</strong><small>{m.role}</small></div><button className="quiet" disabled={busy||m.email===session.user?.email} onClick={()=>void perform(()=>manage('remove',m.email))}>Retirar acceso</button></div>)}</>}</>}{error&&<p role="alert" className="danger">{error}</p>}</section>;
}
