// Synthetic test fixtures only. Never loaded by the application.
import type { Entity, Snapshot } from './model';
export function entity(kind:Entity['kind'],name:string,amount=0,extras:Partial<Entity>={}):Entity{return {id:crypto.randomUUID(),kind,name,amount,currency:'GTQ',apr:null,minimum:0,minimumUSD:0,day:0,start:'',frequency:'monthly',flow:'expense',active:true,overdue:false,note:'',...(kind==='category'?{budgetGroup:'variable' as const}:{}),...extras};}
export function seed():Snapshot{
 const categories=budgetRows().map(([name,enName,amount,budgetGroup])=>entity('category',name,amount,{enName,budgetGroup}));
 categories.push(...[['Higiene',300],['Cabello',300],['Cuidado personal',300],['Ropa',300],['Zapatos',300],['Limpieza',300],['Artículos hogar',300],['Fondo veterinario',300],['Regalos',300],['Emergencias',300]].map(([name,amount])=>entity('category',String(name),Number(amount),{budgetGroup:'provision'})));
 const incomes=[entity('recurring','Employer A',1000,{currency:'USD',flow:'income',day:25}),entity('recurring','Employer B',1000,{currency:'USD',flow:'income',frequency:'semimonthly',start:'2026-10-15',note:''}),entity('recurring','Employer C',1000,{flow:'income',start:'2026-10-01',note:''}),entity('recurring','Contract D',1000,{flow:'income',frequency:'bimonthly',note:''})];
 return {entities:[entity('account','Banco',0),entity('account','Efectivo',0),entity('account','USD',0,{currency:'USD'}),...categories,...incomes,entity('debt','Card A',1000,{apr:20,minimum:1000,day:18,overdue:true,note:''}),entity('debt','Card B',1000,{apr:20,minimum:1000,minimumUSD:1000,day:2,note:''}),entity('debt','Loan C',1000),entity('debt','Loan D',1000),entity('debt','Loan E',1000),entity('debt','Loan F',1000,{note:''}),entity('goal','Mini fondo emergencia',1000,{enName:'Mini emergency fund'}),entity('goal','Fondo emergencia completo',1000,{enName:'Full emergency fund'}),entity('goal','Fondo Pet',1000,{enName:'Pet reserve'}),entity('goal','Inversiones',1000,{enName:'Investments',note:''})],transactions:[],events:[{id:crypto.randomUUID(),name:'Employer B',date:'2026-10-15',amount:1000,currency:'USD',flow:'income',status:'confirmed',sourceId:incomes[1].id},{id:crypto.randomUUID(),name:'Employer A',date:'2026-10-25',amount:1000,currency:'USD',flow:'income',status:'confirmed',sourceId:incomes[0].id},{id:crypto.randomUUID(),name:'Employer B · segundo pago / second payment',date:'',amount:1000,currency:'USD',flow:'income',status:'pending',sourceId:incomes[1].id},{id:crypto.randomUUID(),name:'Employer C · monto y fecha pendientes / amount and date pending',date:'',amount:1000,currency:'GTQ',flow:'income',status:'pending',sourceId:incomes[2].id},{id:crypto.randomUUID(),name:'Card A · mínimo / minimum',date:'2026-10-18',amount:1000,currency:'GTQ',flow:'expense',status:'confirmed',sourceId:''},{id:crypto.randomUUID(),name:'Card B · mínimo / minimum',date:'2026-10-02',amount:1000,currency:'GTQ',flow:'expense',status:'confirmed',sourceId:''}],settings:{budgetRevision:3,language:'es',theme:'dark',fx:7.64136,fxUpdated:'Referencia histórica / Historical reference',fxSource:'reference',displayCurrency:'GTQ',autoFx:false}};
}

export function categoryRenames():[string,string][]{return [['Gastos Person','Apoyo personal'],['Universidad Person','Universidad']];}

export function budgetRows():[string,string,number,'essential'|'variable'|'provision'][] {return [
['Alquiler / hipoteca','Rent / mortgage',300,'essential'],['Electricidad, Internet, etc.','Utilities',300,'essential'],['Supermercado','Groceries',300,'essential'],['Combustible / transporte','Fuel / transport',300,'essential'],['Seguro Carro','Car insurance',300,'essential'],['Seguro / medicinas','Insurance / medicine',300,'essential'],['Internet y móvil','Internet and mobile',300,'essential'],['Ocio','Leisure',300,'variable'],['Comidas fuera','Dining out',300,'variable'],['Streaming / apps','Streaming / apps',300,'variable'],['Renta Madre','Family rent',300,'variable'],['Medicina Madre','Family medicine',300,'essential'],['Papá','Family support',300,'variable'],['Comida / Premios','Pet food / treats',300,'variable'],['Veterinario / Grooming','Vet / grooming',300,'variable'],['Universidad','University',300,'variable'],['Apoyo personal','Personal support',300,'variable']];}
export const budgetAliases:Record<string,string>={'Alquiler / hipoteca':'Vivienda','Electricidad, Internet, etc.':'Servicios','Combustible / transporte':'Transporte','Seguro Carro':'Seguro carro','Seguro / medicinas':'Salud','Internet y móvil':'Telefonía','Ocio':'Entretenimiento','Comidas fuera':'Restaurantes','Streaming / apps':'Suscripciones','Renta Madre':'Renta madre','Medicina Madre':'Medicina madre','Comida / Premios':'Pet comida','Veterinario / Grooming':'Pet veterinario'};
