import {useState} from 'react';
import {X,Plus,Repeat,Check} from 'lucide-react';
import {DatePicker} from './DatePicker';
import {entity} from './seed';
import type {Entity,Transaction,HouseholdMember} from './model';
import type {CopyKey} from './i18n';
export function TransactionEditor({initial,role,entities,members,t,onClose,onSave}:{initial:Transaction;role?:'admin'|'contributor'|'viewer';entities:Entity[];members:HouseholdMember[];t:(k:CopyKey)=>string;onClose:()=>void;onSave:(v:unknown)=>Promise<void>}){
 const [v,set]=useState(initial);const [more,setMore]=useState(false);const [repeat,setRepeat]=useState(false);const [day,setDay]=useState(Number(initial.date.slice(8)));const [flexible,setFlexible]=useState(false);const [categoryName,setCategoryName]=useState('');const [adding,setAdding]=useState(false);const [newCategory,setNewCategory]=useState<Entity|null>(null);const [saving,setSaving]=useState(false);
 const es=t('save')==='Guardar';const say=(a:string,b:string)=>es?a:b;
 const update=(p:Partial<Transaction>)=>set(old=>({...old,...p}));
 const changeDate=(date:string)=>{update({date});if(!repeat&&date)setDay(Number(date.slice(8)));};
 const accounts=entities.filter(e=>e.kind==='account').sort((a,b)=>a.name.localeCompare(b.name));const categories=[...entities.filter(e=>e.kind==='category'),...(newCategory?[newCategory]:[])].sort((a,b)=>a.name.localeCompare(b.name));const sources=entities.filter(e=>e.kind==='recurring'&&e.flow==='income');
 const selectedRecurrence=entities.find(e=>e.id===v.recurrenceId);
 return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="transaction-title"><div className="section-title"><h2 id="transaction-title">{t('add')}</h2><button type="button" className="icon" aria-label={t('close')} onClick={onClose}><X/></button></div><form onSubmit={async e=>{e.preventDefault();setSaving(true);try{const resolvedName=v.name.trim()||categories.find(c=>c.id===v.categoryId)?.name||t(v.type);const nextMonth=new Date(Number(v.date.slice(0,4)),Number(v.date.slice(5,7)),1,12);const nextStart=nextMonth.getFullYear()+"-"+String(nextMonth.getMonth()+1).padStart(2,"0")+"-01";const recurrence=repeat?{...(selectedRecurrence??entity('recurring',v.name)),name:resolvedName,amount:v.amount,currency:v.currency,day,start:selectedRecurrence?.start??nextStart,targetId:v.targetId,txType:v.type,flow:v.type==='income'?'income':'expense',frequency:'monthly',active:true,categoryId:v.categoryId,flexible}:null;await onSave({transaction:{...v,name:v.name.trim()||categories.find(c=>c.id===v.categoryId)?.name||t(v.type),recurrenceId:recurrence?.id??v.recurrenceId},recurrence,category:newCategory});}finally{setSaving(false);}}}>
 <div className="type-tabs">{(['expense','income','payment','transfer','contribution'] as const).filter(type=>!role||role==='admin'||(role==='contributor'?['expense','income']:['expense']).includes(type)).map(type=><button type="button" className={v.type===type?'active':''} key={type} onClick={()=>{setRepeat(false);update({type,recurrenceId:'',eventId:undefined,targetId:'',categoryId:type==='expense'?v.categoryId:''});}}>{t(type)}</button>)}</div>
 <div className="amount-row"><input aria-label={t('amount')} className="amount-input" autoFocus type="number" inputMode="decimal" min="0.01" step="0.01" required value={v.amount||''} placeholder="0.00" onChange={e=>update({amount:Number(e.target.value)})}/><select aria-label={t('currency')} value={v.currency} onChange={e=>update({currency:e.target.value as 'GTQ'|'USD'})}><option>GTQ</option><option>USD</option></select></div>
 {v.type==='expense'&&<><label>{t('category')}<select value={v.categoryId} onChange={e=>update({categoryId:e.target.value})}><option value="">{t('none')}</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{(!role||role==='admin')&&<button type="button" className="quiet" onClick={()=>setAdding(!adding)}><Plus size={15}/>{say('Crear categoría','Create category')}</button>}{adding&&<div className="inline-category"><input aria-label={say('Nombre de categoría','Category name')} maxLength={160} placeholder={say('Emergencias, regalos…','Emergencies, gifts…')} value={categoryName} onChange={e=>setCategoryName(e.target.value)}/><button type="button" className="secondary" disabled={!categoryName.trim()} onClick={()=>{const existing=categories.find(c=>c.name.toLowerCase()===categoryName.trim().toLowerCase());const c=existing??entity('category',categoryName.trim(),0);if(!existing)setNewCategory(c);update({categoryId:c.id});setAdding(false);}}>{t('new')}</button></div>}<div className="category-chips">{[say('Emergencias','Emergencies'),say('Regalos','Gifts')].filter(name=>!role||role==='admin'||categories.some(c=>c.name===name)).map(name=><button type="button" className="badge" key={name} onClick={()=>{const existing=categories.find(c=>c.name===name);const c=existing??entity('category',name,0);if(!existing)setNewCategory(c);update({categoryId:c.id});}}>{name} +</button>)}</div></>}
 {v.type==='income'&&<label>{say('Fuente del ingreso','Income source')}<select value={v.recurrenceId??''} onChange={e=>{const source=sources.find(s=>s.id===e.target.value);update({recurrenceId:e.target.value,...(source?{name:source.name,currency:source.currency,amount:source.amount}:{})});}}><option value="">{say('Otro ingreso','Other income')}</option>{sources.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label>}
 {['transfer','payment','contribution'].includes(v.type)&&<label>{t('target')}<select required value={v.targetId} onChange={e=>update({targetId:e.target.value})}><option value="">{t('none')}</option>{entities.filter(e=>e.kind===(v.type==='transfer'?'account':v.type==='payment'?'debt':'goal')&&e.id!==v.accountId).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label>}
 <label>{say('Descripción (opcional)','Description (optional)')}<input maxLength={160} value={v.name} onChange={e=>update({name:e.target.value})}/></label><div className="form-grid"><label>{t('account')}<select required value={v.accountId} onChange={e=>update({accountId:e.target.value})}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>{t('date')}<DatePicker required value={v.date} onChange={changeDate} es={es}/></label></div>
 {(!role||role==='admin')&&['expense','income','payment'].includes(v.type)&&<details className="optional-panel"><summary><Repeat size={15}/>{say('Repetir cada mes (opcional)','Repeat monthly (optional)')}</summary><label className="checkbox"><input type="checkbox" checked={repeat} onChange={e=>setRepeat(e.target.checked)}/>{say('Programar próximos meses','Schedule future months')}</label>{repeat&&<><label>{say('Día del mes','Day of month')}<input type="number" min="1" max="31" value={day} onChange={e=>setDay(Number(e.target.value))}/></label><label className="checkbox"><input type="checkbox" checked={flexible} onChange={e=>setFlexible(e.target.checked)}/>{say('Fecha flexible: puedo distribuir esta compra','Flexible date: I can spread this purchase')}</label><small>{say('Guardar registra este movimiento y crea una previsión mensual; los futuros pagos requieren confirmación.','Saving records this transaction and creates a monthly forecast; future payments require confirmation.')}</small></>}{selectedRecurrence&&!repeat&&<small>{say('Ya vinculado a una recurrencia. Edita o pausa la plantilla en Recurrentes.','Already linked to a recurrence. Edit or pause its template in Recurring.')}</small>}</details>}
 <button type="button" className="quiet" onClick={()=>setMore(!more)}>{more?'−':'+'} {say('Más detalles','More details')}</button>{more&&<><div className="form-grid"><label>{t('member')}<select value={v.member} onChange={e=>update({member:e.target.value as Transaction['member']})}>{[...new Set(['Shared',...members.map(m=>m.name),v.member])].map(m=><option key={m}>{m}</option>)}</select></label><label>{t('share')}<input type="number" min="0" max="100" value={v.share} onChange={e=>update({share:Number(e.target.value)})}/></label></div><label>{t('note')}<textarea maxLength={2000} value={v.note} onChange={e=>update({note:e.target.value})}/></label></>}{v.currency==='USD'&&<label>{t('fx')}<input type="number" min="0.00001" max="100" step="0.00001" required value={v.fx} onChange={e=>update({fx:Number(e.target.value)})}/></label>}
 <div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>{t('cancel')}</button><button className="primary" disabled={saving}><Check size={17}/>{t('save')}</button></div></form></section></div>;
}
